/**
 * Simulate 100,000 random guessers on the actual 50 speaker pool.
 * For each batch checkpoint (5, 10, ..., 50 clips), records the running
 * score distribution across all trials, then writes a static TypeScript
 * constant to lib/randomDistributions.ts.
 *
 * Run: node scripts/simulateRandom.js
 */

const fs = require('fs');
const path = require('path');

// True Kinsey scores for all 50 speakers (from scripts/seed.ts)
const TRUE_SCORES = [
  1, 1, 4, 1, 5, 5, 1, 3, 4, 1,
  2, 4, 5, 3, 1, 5, 1, 5, 5, 1,
  1, 3, 1, 5, 1, 5, 1, 1, 4, 2,
  1, 3, 1, 5, 2, 1, 5, 5, 1, 1,
  2, 1, 3, 5, 1, 5, 2, 4, 1, 1,
];

const TRIALS = 100_000;
const CHECKPOINTS = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50];

// distributions[nClips][score_as_halfpoints] = count
const counts = {};
for (const n of CHECKPOINTS) counts[n] = {};

// Fisher-Yates shuffle (in-place)
function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
}

const pool = [...TRUE_SCORES];

console.log(`Running ${TRIALS.toLocaleString()} trials...`);
const t0 = Date.now();

for (let trial = 0; trial < TRIALS; trial++) {
  shuffle(pool);
  let halfPts = 0; // accumulate in integer half-points to avoid float accumulation

  for (let i = 0; i < 50; i++) {
    const guess = Math.floor(Math.random() * 5) + 1; // uniform 1-5
    const diff = Math.abs(guess - pool[i]);
    halfPts += diff === 0 ? 2 : diff === 1 ? 1 : 0;

    const n = i + 1;
    if (n % 5 === 0) {
      counts[n][halfPts] = (counts[n][halfPts] || 0) + 1;
    }
  }
}

console.log(`Done in ${((Date.now() - t0) / 1000).toFixed(1)}s`);

// Normalise to probabilities (using half-point keys)
const distributions = {};
for (const n of CHECKPOINTS) {
  distributions[n] = {};
  for (const [hp, count] of Object.entries(counts[n])) {
    distributions[n][hp] = count / TRIALS;
  }
}

// Emit TypeScript file
const lines = [
  '// Auto-generated by scripts/simulateRandom.js — do not edit manually.',
  `// ${TRIALS.toLocaleString()} trials × 50 speakers, scored at each 5-clip checkpoint.`,
  '// Keys: outer = nClips (5..50 step 5), inner = score in half-points (integer), value = probability.',
  '',
  '// e.g. RANDOM_DISTRIBUTIONS[10][7] = prob of scoring 3.5 pts after 10 clips (3.5 × 2 = 7 half-pts)',
  'export const RANDOM_DISTRIBUTIONS: Record<number, Record<number, number>> = {',
];

for (const n of CHECKPOINTS) {
  const entries = Object.entries(distributions[n])
    .map(([hp, p]) => `    ${hp}: ${p.toFixed(6)}`)
    .join(',\n');
  lines.push(`  ${n}: {\n${entries}\n  },`);
}

lines.push('};', '');

const outPath = path.join(__dirname, '..', 'lib', 'randomDistributions.ts');
fs.writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log(`Written to ${outPath}`);
